name: Deploy to Github Pages
on:
    push:
        branches:
            - main
concurrency:
    group: pages
    cancel-in-progress: true

permissions:
    contents: read
    pages: write
    id-token: write

jobs:
    deploy:
        name: Deploy
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: 21
                  cache: 'npm'

            - name: Clean Install
              run: npm ci

            - name: Build
              run: npm run build

            - name: Deploy 🚀
              uses: JamesIves/github-pages-deploy-action@v4
              with:
                  folder: build # The folder the action should deploy.
                  branch: gh-pages
                  commit-message: 'ci: Deploy'
